server {
    listen 443 ssl;
    http2 on;

    server_name app.x25.shop;

    ssl_certificate     /etc/ssl/app/app.x25.shop.crt;
    ssl_certificate_key /etc/ssl/app/app.x25.shop.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/app_access.log main;
    error_log  /var/log/nginx/app_error.log warn;

    # WebDAV
    location /shared {
        root /srv;

        dav_methods PUT DELETE MKCOL COPY MOVE;
        create_full_put_path on;
        dav_access user:rw group:rw all:r;

        auth_basic "Shared Folder";
        auth_basic_user_file /etc/nginx/auth/app.htpasswd;

        client_max_body_size 2G;
    }

    # Public webhooks
    location ~ ^/(webhook|webhook-test)/ {
        proxy_pass http://127.0.0.1:3000;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # Protected app
    location / {
        auth_basic "restricted";
        auth_basic_user_file /etc/nginx/auth/app.htpasswd;

        proxy_pass http://127.0.0.1:3000;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}

