server {
    listen 80;
listen 443 ssl;

#   server_name _; # Or your EC2 Public IP / Domain
    server_name app.x25.shop; # Or your EC2 Public IP / Domain

# Point to the files we just made
    ssl_certificate /etc/nginx/webdav.crt;
    ssl_certificate_key /etc/nginx/webdav.key;





    # Directory for WebDAV files
    root /var/www/webdav;

    location / {
        # Standard WebDAV methods
        dav_methods PUT DELETE MKCOL COPY MOVE;
        
        # Permissions for new files
        dav_access user:rw group:rw all:r;

        # Tuning for file transfers
        client_max_body_size 0;      # No limit on upload size
        create_full_put_path on;     # Allow creating subfolders
        autoindex on;                # Show file list in browser

        # Authentication
        auth_basic "WebDAV Storage";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}
